version: '3'

services:

  php:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: otus/php-${APP_NAME}
    container_name: php_${APP_NAME}
    volumes:
       - ./code:/data
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: otus/nginx-${APP_NAME}
    container_name: webserver_${APP_NAME}
    ports:
      - ${NGINX_PORT80}:80
      - ${NGINX_PORT443}:443
    volumes:
       - ./code:/data/
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network


  db:
    build:
      context: ./postgre
    #    restart: always
    image: otus/postgre-${APP_NAME}
    container_name: postgre_${APP_NAME}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./../logs/dbdata/postgresql:/var/lib/postgresql
      - ./../logs/postgresql-log:/var/log/postgresql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge