version: '3'

services:

  php:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: otus/php-${APP_NAME}
    container_name: php_${APP_NAME}
    volumes:
       - ./code:/data
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: otus/nginx-${APP_NAME}
    container_name: webserver_${APP_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./code:/data/
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network


  db:
    build:
      context: ./postgre
    #    restart: always
    image: otus/postgre-${APP_NAME}
    container_name: postgre_${APP_NAME}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./../logs/dbdata/postgresql:/var/lib/postgresql
      - ./../logs/postgresql-log:/var/log/postgresql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.7.5-management
    working_dir: /app
    hostname: rabbit-mq
    container_name: 'rabbit-mq'
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

  redis :
    image: redis:latest
    container_name : ${REDIS_SERVER}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - app-network


networks:
  app-network:
    driver: bridge